parameters:
    pim_extended_attribute_type.completeness.checker.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Completeness\Checker\TextCollectionCompleteChecker
    pim_extended_attribute_type.completeness.mask_item_generator.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Completeness\MaskItemGenerator\TextCollectionMaskItemGenerator

services:
    pim_extended_attribute_type.completeness.checker.text_collection:
        class: '%pim_extended_attribute_type.completeness.checker.text_collection.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }

    akeneo.pim.enrichment.completeness.mask_item_generator.text_collection:
        class: '%pim_extended_attribute_type.completeness.mask_item_generator.text_collection.class%'
        tags: [{ name: akeneo.pim.enrichment.completeness.mask_item_generator }]
